#define OLED_MISO           32
#define OLED_MOSI           23
#define OLED_SCLK           18
#define OLED_CS             5
#define OLED_DC             19
#define OLED_RST            4
#define OLED_PWR            33
#define PWR_ON              2
#define TOUCH_PWR           32
#define TOUCH_PIN           15
#define RTC_SDA             26
#define RTC_SCL             25
#define ADC_PIN             34
#define IR_RECV             13

#define KEY_R   0
#define KEY_D   0
#define KEY_L   0
#define KEY_U   0
#define KEY_A   0
#define KEY_B   0